openapi: 3.0.0
info:
  title: Título da Documentação
  description: Descrição da API
  version: 1.0.0
paths:
  /api/v1/endpoint:
    get:
      summary: Descrição do que essa rota faz
      responses:
        200:
          description: Sucesso ao retornar dados
